environment:
  version_suffix: alpha
  
version: 1.0.1-$(version_suffix){build}

# branches to build
branches:
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
# Valeriy1991: Because tags created by GitHub Release deployment configuration
skip_tags: true

image: Visual Studio 2017

configuration: Release

# Patch .NET Core/Standard *.csproj files for versioning:
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

# restore Nuget packages before build:
before_build:
- nuget restore

build:
  publish_nuget: true # package projects with .nuspec files and push to artifacts
  #publish_nuget_symbols: true # generate and publish NuGet symbol packages
  verbosity: minimal

artifacts:
 - path: '**\*.nupkg' 

deploy:
 - provider: NuGet
   name: production
   server: 
   api_key:
    secure: hCYZb1qY+PIMKQZ21VS2lkCBSvrEUzFvEXrV/mTmpa+f5DDh4YtGowrmOAhpVrD7
   skip_symbols: true
   artifact: /.*\.nupkg/

 - provider: GitHub
   name: production-GitHub
   description: ''
   artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
   draft: true
   prerelease: true # TODO: (version_suffix != string.empty) ? true : false
   auth_token:
     secure: cXU/5uMu5hDP4h2I7NTHUQ4qaDY67P9hDwNVe2hwEijidAJXQe6zX1f1CInMYOcV
   on:
     branch: master                # release from master branch only
     #appveyor_repo_tag: true       # deploy on tag push only 
  
# send notification to Slack about build results
notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: releases
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: true